stages:
  - infra_validate
  - infra_plan
  - infra_apply
  - test
  - build
  - deploy

variables:
  IMAGE_STAGING: $CI_REGISTRY_IMAGE:staging
  IMAGE_PROD: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

.terraform_base:
  image: 
    name: hashicorp/terraform:1.14
    entrypoint: [""]
  before_script:
    - cd terraform
    - terraform init

tf_validate:
  extends: .terraform_base
  stage: infra_validate
  script:
    - terraform validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - terraform/*
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main"
      changes:
        - terraform/*

tf_plan:
  extends: .terraform_base
  stage: infra_plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/tfplan
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - terraform/*

tf_apply:
  extends: .terraform_base
  stage: infra_apply
  script:
    - terraform apply -auto-approve tfplan
    - echo "SERVER_IP=$(terraform output -raw server_public_ip)" > ../server.env
  artifacts:
    reports:
      dotenv: server.env  
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - terraform/*
      when: manual 
  dependencies:
    - tf_plan  

test_api:
  stage: test
  image: node:20-slim
  services:
    - name: postgres:15-alpine
      alias: postgres
  variables:
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpassword
    POSTGRES_DB: ridebalance_test
    # Sobreescribir las de .env.test
    DATABASE_URL: "postgresql://testuser:testpassword@postgres:5432/ridebalance_test"
    JWT_SECRET: "test-secret"
  script:
    - apt-get update -y && apt-get install -y openssl
    - npm ci
    - npx prisma generate
    - npx prisma db push --accept-data-loss
    - npm test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'develop'
    - if: $CI_COMMIT_BRANCH == 'main'

build_staging:
  stage: build
  image: docker:28.2.2
  services:
    - docker:28.2.2-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_STAGING .
    - docker push $IMAGE_STAGING
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'

build_production:
  stage: build
  image: docker:28.2.2
  services:
    - docker:28.2.2-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_PROD .
    - docker push $IMAGE_PROD
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

deploy_staging:
  stage: deploy
  script:
    - echo "Desplegando a servidor de pruebas (Staging)"
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
  environment: staging

deploy_production:
  stage: deploy
  image: alpine:latest
  dependencies:
    - tf_apply
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p ~/ssl"
    - scp -o StrictHostKeyChecking=no $SSL_CERT $SERVER_USER@$SERVER_HOST:~/ssl/cert.pem
    - scp -o StrictHostKeyChecking=no $SSL_KEY $SERVER_USER@$SERVER_HOST:~/ssl/key.pem
    
    - scp -o StrictHostKeyChecking=no docker-compose.yml nginx.conf $SERVER_USER@$SERVER_HOST:~/

    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "

      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&

      export IMAGE_PROD=$IMAGE_PROD &&
      export PRODUCTION_DATABASE_URL=$PRODUCTION_DATABASE_URL &&
      export PRODUCTION_JWT_SECRET=$PRODUCTION_JWT_SECRET &&
      export PORT=$PORT &&

      docker compose pull &&

      docker compose run --rm ride-balance-api npx prisma migrate deploy &&

      docker compose up -d &&

      docker compose exec -T nginx nginx -s reload &&

      docker image prune -f
      "
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

    - when: never  

  environment: 
    name: production
    url: https://ridebalance.com
  
