
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ride-balance-api-prod
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
